export const blockIndex = {
    'dirt': { UV: [0, .9], transparent: false, sound: ['dirt'] },
    'grass': { UV: [.1, .9], transparent: false, sound: ['grass'] },
    'stone': { UV: [.2, .9], transparent: false, sound: ['stone'] },
    'bedrock': { UV: [.3, .9], transparent: false, sound: ['stone'], unbreakable: true },
    'log': { UV: [.4, .9], transparent: false, sound: ['wood', 'stone'] },
    'leaves': { UV: [.5, .9], transparent: true, sound: ['grass'] },
    'coal ore': { UV: [.6, .9], transparent: false, sound: ['stone'] },
    'iron ore': { UV: [.7, .9], transparent: false, sound: ['stone'] },
    'diamond ore': { UV: [.8, .9], transparent: false, sound: ['stone'] },
    'gold ore': { UV: [.9, .9], transparent: false, sound: ['stone'] },
    'ruby ore': { UV: [0, .8], transparent: false, sound: ['stone'] },
    'sapphire ore': { UV: [.1, .8], transparent: false, sound: ['stone'] },
    'glass': { UV: [.2, .8], transparent: true, sound: ['stone', 'wood'] },
    'snow': { UV: [.3, .8], transparent: false, sound: ['dirt'] },
    'planks': { UV: [.4, .8], transparent: false, sound: ['wood', 'stone'] },
    'sand': { UV: [.5, .8], transparent: false, sound: ['dirt'] },
    'water': { UV: [.6, .8], transparent: true, sound: [], unbreakable: true },
    'cobble': { UV: [.7, .8], transparent: false, sound: ['stone'] },
    'magma': { UV: [.8, .8], transparent: false, sound: ['stone'] },
    'lava': { UV: [.9, .8], transparent: false, sound: ['stone'] },
    'bloodstone': { UV: [0, .7], transparent: false, sound: ['squish', 'stone'] },
    'bones 1': { UV: [.1, .7], transparent: false, sound: ['squish', 'stone'] },
    'bones 2': { UV: [.2, .7], transparent: false, sound: ['squish', 'stone'] },
    'blood': { UV: [.3, .7], transparent: true, sound: [] },
    'bone': { UV: [.4, .7], transparent: false, sound: ['stone', 'wood'] },
}